import { io } from '/private/tmp/claude-501/-Users-advikgupta-Desktop-Web-Development-multiplayer-wordle/b9825b39-3803-4e7f-af5b-c87175a1bf99/scratchpad/playbattle/node_modules/socket.io-client/build/cjs/index.js';
const URL = 'http://localhost:4361';
const mk = (id, name) => io(URL, { transports: ['websocket'], auth: { profile: { id, name } } });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const emit = (s,e,arg) => new Promise(r => arg === undefined ? s.emit(e,r) : s.emit(e,arg,r));

const a = mk('w1','ann'), b = mk('w2','ben'), c = mk('w3','cat');
let sA=null; a.on('room:state', s=>sA=s);
let kicked=null; c.on('room:removed', r=>kicked=r);
await wait(800);
const code = (await emit(a,'room:create',{maxPlayers:4,rounds:1,secondsPerRound:0})).data.code;
await emit(b,'room:join',code); await emit(c,'room:join',code);
await wait(300);
console.log('first vote ->', JSON.stringify(await emit(a,'room:votekick','w3')));
await wait(200);
console.log('vote pending:', JSON.stringify(sA.votekicks.map(v=>({t:v.targetName,v:v.votes.length,r:v.required}))));
await emit(a,'room:votekick','w3');
await wait(200);
console.log('repeat vote does not count:', sA.votekicks[0].votes.length);
console.log('target cannot vote themselves out ->', JSON.stringify(await emit(c,'room:votekick','w3')));
await emit(b,'room:votekick','w3');
await wait(400);
console.log('removed after second voter:', JSON.stringify(kicked), '| players:', sA.players.length, '| votes cleared:', sA.votekicks.length);
console.log('rejoin blocked ->', JSON.stringify(await emit(c,'room:join',code)));

console.log();
console.log('=== auto start after a leaver ===');
const d = mk('w4','dot');
await wait(600);
await emit(d,'room:join',code);
await wait(200);
await emit(a,'room:ready',true); await emit(b,'room:ready',true);
await wait(300);
console.log('waiting on dot:', sA.phase);
await emit(d,'room:leave');
await wait(500);
console.log('started once dot left:', sA.phase, 'round', sA.round);

console.log();
console.log('=== skip ===');
console.log('skip ->', JSON.stringify(await emit(a,'game:skip')));
await wait(200);
console.log('resigned flag:', sA.players.find(p=>p.profile.id==='w1').resigned);
console.log('guess after skip ->', JSON.stringify(await emit(a,'game:guess','about')));
console.log('skip twice ->', JSON.stringify(await emit(a,'game:skip')));
console.log('ben skips ->', JSON.stringify(await emit(b,'game:skip')));
await wait(700);
console.log('round over when everyone skipped:', sA.phase, '| answer revealed:', sA.answer !== null);

console.log();
console.log('=== spoiler guard ===');
const e = mk('w5','eve'), f = mk('w6','fay');
let sE=null; e.on('room:state', s=>sE=s);
await wait(700);
const c2 = (await emit(e,'room:create',{rounds:1,maxGuesses:6,secondsPerRound:0})).data.code;
await emit(f,'room:join',c2);
await emit(e,'room:ready',true); await emit(f,'room:ready',true);
await wait(400);
for (const w of ['about','other','plant','three','world','music']) await emit(f,'game:guess',w);
await wait(200);
const answer = sE.players.find(p=>p.profile.id==='w6') ? null : null;
const fState = await new Promise(r => { f.once('room:state', r); f.emit('presence:ping', ()=>{}); });
const ans = fState.answer;
console.log('fay knows the answer:', ans !== null);
console.log('say the answer ->', JSON.stringify(await emit(f,'chat:send', 'the word is ' + ans)));
console.log('say it upper/spaced ->', JSON.stringify(await emit(f,'chat:send', ans.toUpperCase().split('').join(' '))));
console.log('normal chat still ok ->', JSON.stringify(await emit(f,'chat:send','good luck')));
process.exit(0);
