export const ANAGRAM_WORDS = [
  'ace', 'ache', 'aches', 'acid', 'acids', 'acorn', 'acre', 'acres', 'act', 'acted',
  'actor', 'acts', 'add', 'adds', 'afar', 'age', 'aged', 'ages', 'ago', 'aid',
  'aide', 'aids', 'ail', 'aim', 'aims', 'air', 'aired', 'airs', 'ale', 'alert',
  'alien', 'align', 'alike', 'alive', 'all', 'alley', 'allow', 'alloy', 'ally', 'alms',
  'aloe', 'alone', 'along', 'aloud', 'alter', 'amber', 'amble', 'amend', 'ample', 'amuse',
  'anchor', 'angel', 'anger', 'angle', 'ankle', 'answer', 'ant', 'ante', 'ants', 'anvil',
  'ape', 'apes', 'apex', 'apple', 'apply', 'apron', 'apt', 'arc', 'arch', 'arcs',
  'are', 'area', 'arena', 'argue', 'arid', 'arise', 'arm', 'armed', 'army', 'arose',
  'array', 'arrow', 'art', 'artist', 'arts', 'ash', 'aside', 'ask', 'asked', 'asleep',
  'aspect', 'ate', 'atlas', 'atom', 'atoms', 'attic', 'auto', 'avert', 'avoid', 'await',
  'awake', 'award', 'aware', 'away', 'awful', 'axe', 'axis', 'bad', 'badge', 'badly',
  'bag', 'bags', 'bail', 'bait', 'bake', 'baker', 'bakes', 'bald', 'bale', 'ball',
  'balm', 'band', 'bands', 'bane', 'bang', 'bank', 'banks', 'bar', 'bare', 'barge',
  'bark', 'barn', 'bars', 'base', 'based', 'bases', 'basic', 'basin', 'basis', 'bat',
  'batch', 'bath', 'bats', 'bay', 'bays', 'beach', 'bead', 'beam', 'bean', 'bear',
  'beard', 'beast', 'beat', 'beats', 'bed', 'beds', 'bee', 'been', 'beer', 'bees',
  'beet', 'beg', 'begin', 'begs', 'bell', 'belt', 'bench', 'bend', 'bent', 'berry',
  'best', 'bet', 'bets', 'bid', 'big', 'bike', 'bile', 'bill', 'bin', 'bind',
  'bird', 'birds', 'bit', 'bite', 'bits', 'black', 'blade', 'blame', 'bland', 'blank',
  'blast', 'blaze', 'bleak', 'blend', 'bless', 'blind', 'blink', 'block', 'blond', 'blood',
  'bloom', 'blow', 'blue', 'blunt', 'blur', 'blush', 'board', 'boast', 'boat', 'boats',
  'body', 'bog', 'boil', 'bold', 'bolt', 'bomb', 'bond', 'bone', 'bones', 'bonus',
  'book', 'books', 'boom', 'boost', 'boot', 'boots', 'bore', 'born', 'borne', 'both',
  'bound', 'bow', 'bowl', 'box', 'boy', 'boys', 'brace', 'braid', 'brain', 'brake',
  'bran', 'brand', 'brass', 'brave', 'bread', 'break', 'breed', 'brew', 'brick', 'bride',
  'brief', 'bright', 'brim', 'bring', 'brink', 'brisk', 'broad', 'broil', 'broke', 'brook',
  'broom', 'brow', 'brown', 'brush', 'buck', 'bud', 'buds', 'buff', 'bug', 'bugs',
  'build', 'built', 'bulb', 'bulk', 'bull', 'bump', 'bunch', 'bundle', 'bunk', 'burn',
  'burst', 'bus', 'bush', 'busy', 'but', 'butter', 'buy', 'buzz', 'cab', 'cabin',
  'cable', 'cage', 'cake', 'cakes', 'calf', 'call', 'calm', 'came', 'camel', 'camp',
  'can', 'candle', 'cane', 'canoe', 'cap', 'cape', 'caps', 'car', 'card', 'cards',
  'care', 'cargo', 'carol', 'carry', 'cars', 'cart', 'carve', 'case', 'cash', 'cask',
  'cast', 'castle', 'cat', 'catch', 'cats', 'cattle', 'cause', 'cave', 'caves', 'cease',
  'cedar', 'ceiling', 'cell', 'cells', 'cent', 'cents', 'chain', 'chair', 'chalk', 'champ',
  'chance', 'change', 'chant', 'chaos', 'chap', 'chapel', 'char', 'charm', 'chart', 'chase',
  'chat', 'cheap', 'cheat', 'check', 'cheek', 'cheer', 'chess', 'chest', 'chew', 'chick',
  'chief', 'child', 'chill', 'chin', 'chip', 'choice', 'choir', 'choke', 'chop', 'chord',
  'chose', 'chunk', 'churn', 'cider', 'cigar', 'cinema', 'circle', 'city', 'civic', 'civil',
  'claim', 'clam', 'clamp', 'clan', 'clap', 'clash', 'clasp', 'class', 'claw', 'clay',
  'clean', 'clear', 'clerk', 'click', 'cliff', 'climb', 'cling', 'clip', 'cloak', 'clock',
  'clone', 'close', 'cloth', 'cloud', 'clout', 'clown', 'club', 'clue', 'clump', 'coach',
  'coal', 'coast', 'coat', 'coats', 'cocoa', 'code', 'codes', 'coffee', 'coin', 'coins',
  'cold', 'collar', 'colon', 'color', 'colt', 'comb', 'combat', 'come', 'comedy', 'comet',
  'comfort', 'comic', 'coming', 'comma', 'common', 'cone', 'cook', 'cool', 'cope', 'copper',
  'copy', 'coral', 'cord', 'core', 'cork', 'corn', 'corner', 'cost', 'cot', 'couch',
  'cough', 'could', 'count', 'county', 'coup', 'court', 'cousin', 'cover', 'cow', 'cows',
  'crab', 'crack', 'craft', 'cramp', 'crane', 'crash', 'crate', 'crawl', 'crazy', 'cream',
  'creek', 'creep', 'crest', 'crew', 'crib', 'cried', 'crime', 'crisp', 'crop', 'cross',
  'crowd', 'crown', 'crude', 'cruel', 'crumb', 'crush', 'crust', 'cry', 'cube', 'cubic',
  'cue', 'cuff', 'cult', 'cup', 'cups', 'curb', 'cure', 'curl', 'curse', 'curve',
  'cut', 'cute', 'cuts', 'cycle', 'dad', 'daily', 'dairy', 'dam', 'damp', 'dance',
  'dare', 'dark', 'darn', 'dart', 'dash', 'data', 'date', 'dawn', 'day', 'days',
  'dead', 'deaf', 'deal', 'dealt', 'dean', 'dear', 'death', 'debate', 'debt', 'decade',
  'decay', 'deck', 'decor', 'deed', 'deem', 'deep', 'deer', 'defeat', 'defend', 'degree',
  'delay', 'delta', 'demand', 'den', 'dense', 'dent', 'deny', 'depart', 'depth', 'desert',
  'design', 'desk', 'detail', 'detect', 'device', 'devil', 'dial', 'diary', 'dice', 'die',
  'diet', 'dig', 'digit', 'dim', 'dime', 'dine', 'dinner', 'dip', 'dirt', 'dirty',
  'disc', 'dish', 'disk', 'ditch', 'dive', 'divide', 'dock', 'dog', 'dogs', 'doll',
  'dome', 'done', 'donor', 'door', 'dose', 'dot', 'dots', 'double', 'doubt', 'dough',
  'dove', 'down', 'dozen', 'draft', 'drag', 'drain', 'drama', 'drank', 'draw', 'drawn',
  'dream', 'dress', 'dried', 'drift', 'drill', 'drink', 'drip', 'drive', 'drop', 'drove',
  'drug', 'drum', 'dry', 'duck', 'due', 'duel', 'duke', 'dull', 'dumb', 'dump',
  'dune', 'dusk', 'dust', 'duty', 'dwarf', 'dwell', 'dye', 'each', 'eager', 'eagle',
  'ear', 'early', 'earn', 'earth', 'ease', 'east', 'easy', 'eat', 'eaten', 'eats',
  'echo', 'edge', 'edit', 'eel', 'effort', 'egg', 'eggs', 'eight', 'either', 'elbow',
  'elder', 'elect', 'elite', 'else', 'elude', 'email', 'ember', 'embers', 'emit', 'empty',
  'end', 'ends', 'enemy', 'energy', 'engine', 'enjoy', 'enter', 'entry', 'equal', 'equip',
  'era', 'erase', 'error', 'essay', 'evade', 'even', 'event', 'ever', 'every', 'evil',
  'exact', 'exam', 'excel', 'exist', 'exit', 'expand', 'expert', 'extra', 'eye', 'eyes',
  'fable', 'face', 'fact', 'facts', 'fade', 'fail', 'faint', 'fair', 'faith', 'fake',
  'fall', 'false', 'fame', 'family', 'famous', 'fan', 'fancy', 'far', 'fare', 'farm',
  'fast', 'fat', 'fatal', 'fate', 'father', 'fault', 'favor', 'fear', 'feast', 'feat',
  'feed', 'feel', 'feet', 'fell', 'felt', 'fence', 'fern', 'ferry', 'fetch', 'fever',
  'few', 'fiber', 'field', 'fierce', 'fifth', 'fight', 'file', 'fill', 'film', 'filter',
  'final', 'find', 'fine', 'finger', 'finish', 'fire', 'firm', 'first', 'fish', 'fist',
  'fit', 'five', 'fix', 'flag', 'flame', 'flash', 'flat', 'flaw', 'flee', 'fleet',
  'flesh', 'flew', 'flick', 'flight', 'fling', 'flint', 'flip', 'float', 'flock', 'flood',
  'floor', 'flour', 'flow', 'flower', 'fluid', 'flush', 'flute', 'fly', 'foam', 'focus',
  'fog', 'foil', 'fold', 'folk', 'follow', 'fond', 'font', 'food', 'fool', 'foot',
  'for', 'force', 'ford', 'forest', 'forge', 'fork', 'form', 'fort', 'forth', 'forty',
  'forum', 'found', 'four', 'fox', 'frame', 'fraud', 'free', 'fresh', 'friend', 'fright',
  'frog', 'from', 'front', 'frost', 'frown', 'froze', 'fruit', 'fry', 'fuel', 'full',
  'fun', 'fund', 'funny', 'fur', 'fury', 'fuse', 'gain', 'gala', 'gale', 'game',
  'games', 'gap', 'garage', 'garden', 'gas', 'gate', 'gather', 'gauge', 'gave', 'gaze',
  'gear', 'gem', 'gene', 'genre', 'gentle', 'germ', 'get', 'ghost', 'giant', 'gift',
  'gig', 'gill', 'girl', 'give', 'given', 'glad', 'glance', 'glare', 'glass', 'gleam',
  'glide', 'globe', 'gloom', 'glory', 'glove', 'glow', 'glue', 'goal', 'goat', 'god',
  'gods', 'gold', 'golf', 'gone', 'good', 'goose', 'gown', 'grab', 'grace', 'grade',
  'grain', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grave', 'gray', 'graze',
  'great', 'greed', 'green', 'greet', 'grew', 'grey', 'grid', 'grief', 'grill', 'grim',
  'grin', 'grind', 'grip', 'grit', 'groan', 'grocer', 'groom', 'groove', 'gross', 'ground',
  'group', 'grove', 'grow', 'grown', 'growth', 'guard', 'guess', 'guest', 'guide', 'guild',
  'guilt', 'guitar', 'gulf', 'gum', 'gun', 'gust', 'guy', 'gym', 'habit', 'hail',
  'hair', 'half', 'hall', 'halt', 'ham', 'hand', 'handle', 'hang', 'happy', 'harbor',
  'hard', 'hare', 'harm', 'harp', 'harsh', 'harvest', 'has', 'haste', 'hat', 'hatch',
  'hate', 'haul', 'have', 'hawk', 'hay', 'hazard', 'haze', 'head', 'heal', 'health',
  'heap', 'hear', 'heard', 'heart', 'heat', 'heavy', 'hedge', 'heel', 'height', 'held',
  'hell', 'hello', 'helm', 'help', 'hen', 'her', 'herb', 'herd', 'here', 'hero',
  'hers', 'hide', 'high', 'hike', 'hill', 'hint', 'hip', 'hire', 'hit', 'hive',
  'hobby', 'hockey', 'hold', 'hole', 'hollow', 'holy', 'home', 'honest', 'honey', 'honor',
  'hood', 'hoof', 'hook', 'hop', 'hope', 'horn', 'horse', 'hose', 'host', 'hot',
  'hotel', 'hound', 'hour', 'house', 'hover', 'how', 'howl', 'hub', 'hug', 'huge',
  'hull', 'human', 'humble', 'humor', 'hunt', 'hurry', 'hurt', 'hut', 'ice', 'icon',
  'idea', 'ideal', 'idle', 'idol', 'image', 'imply', 'inch', 'income', 'index', 'inner',
  'input', 'insect', 'inside', 'intact', 'into', 'iron', 'irony', 'island', 'issue', 'item',
  'ivory', 'ivy', 'jacket', 'jail', 'jam', 'jar', 'jaw', 'jazz', 'jeans', 'jelly',
  'jet', 'jewel', 'job', 'join', 'joint', 'joke', 'jolly', 'journey', 'joy', 'judge',
  'juice', 'july', 'jump', 'june', 'jungle', 'junior', 'junk', 'jury', 'just', 'keen',
  'keep', 'kept', 'kettle', 'key', 'keys', 'kick', 'kid', 'kill', 'kin', 'kind',
  'king', 'kiss', 'kit', 'kite', 'knee', 'kneel', 'knew', 'knife', 'knight', 'knit',
  'knob', 'knock', 'knot', 'know', 'known', 'lab', 'label', 'labor', 'lace', 'lack',
  'lad', 'ladder', 'lady', 'lag', 'lake', 'lamb', 'lamp', 'land', 'lane', 'lap',
  'large', 'last', 'late', 'later', 'laugh', 'launch', 'law', 'lawn', 'laws', 'lay',
  'layer', 'lazy', 'lead', 'leaf', 'league', 'leak', 'lean', 'leap', 'learn', 'lease',
  'least', 'leave', 'led', 'left', 'leg', 'legal', 'lemon', 'lend', 'length', 'lens',
  'lent', 'less', 'lesson', 'let', 'letter', 'level', 'lever', 'liar', 'lid', 'lie',
  'life', 'lift', 'light', 'like', 'lily', 'limb', 'lime', 'limit', 'line', 'link',
  'lion', 'lip', 'liquid', 'list', 'listen', 'lit', 'live', 'liver', 'load', 'loaf',
  'loan', 'lobby', 'local', 'lock', 'lodge', 'log', 'logic', 'lone', 'long', 'look',
  'loop', 'loose', 'lord', 'lose', 'loss', 'lost', 'lot', 'loud', 'love', 'low',
  'loyal', 'luck', 'lump', 'lunch', 'lung', 'lure', 'lush', 'luxury', 'lying', 'mad',
  'made', 'magic', 'magnet', 'maid', 'mail', 'main', 'major', 'make', 'male', 'mall',
  'malt', 'man', 'manage', 'mane', 'manner', 'manor', 'many', 'map', 'maple', 'marble',
  'march', 'mare', 'margin', 'marine', 'mark', 'market', 'marry', 'marsh', 'mask', 'mass',
  'mast', 'master', 'mat', 'match', 'mate', 'math', 'matter', 'maze', 'meadow', 'meal',
  'mean', 'meant', 'meat', 'medal', 'media', 'medic', 'meet', 'melon', 'melt', 'member',
  'memory', 'men', 'mend', 'menu', 'mercy', 'mere', 'merge', 'merit', 'merry', 'mesh',
  'mess', 'metal', 'meter', 'method', 'middle', 'midst', 'might', 'mild', 'mile', 'milk',
  'mill', 'mind', 'mine', 'mineral', 'minor', 'mint', 'minus', 'minute', 'mirror', 'miss',
  'mist', 'mix', 'mob', 'mode', 'model', 'modest', 'moist', 'mold', 'mole', 'moment',
  'money', 'monk', 'month', 'mood', 'moon', 'moral', 'more', 'morning', 'most', 'motel',
  'moth', 'mother', 'motion', 'motor', 'mount', 'mouse', 'mouth', 'move', 'movie', 'much',
  'mud', 'mule', 'music', 'must', 'mute', 'nail', 'name', 'nap', 'narrow', 'nation',
  'native', 'nature', 'naval', 'near', 'neat', 'neck', 'need', 'needle', 'neglect', 'nerve',
  'nest', 'net', 'never', 'new', 'news', 'next', 'nice', 'niche', 'night', 'nine',
  'noble', 'node', 'noise', 'none', 'noon', 'nor', 'norm', 'north', 'nose', 'note',
  'noun', 'novel', 'now', 'nurse', 'nut', 'oak', 'oath', 'obey', 'object', 'ocean',
  'odd', 'odds', 'odor', 'off', 'offer', 'office', 'often', 'oil', 'old', 'olive',
  'omit', 'once', 'one', 'onion', 'only', 'onto', 'open', 'opera', 'oral', 'orange',
  'orbit', 'orchard', 'order', 'organ', 'origin', 'other', 'otter', 'ought', 'ounce', 'our',
  'out', 'outer', 'oval', 'oven', 'over', 'owe', 'owl', 'own', 'owner', 'oxygen',
  'pace', 'pack', 'pad', 'page', 'paid', 'pail', 'pain', 'paint', 'pair', 'pale',
  'palm', 'pan', 'panel', 'panic', 'pants', 'paper', 'parade', 'parcel', 'pardon', 'parent',
  'park', 'part', 'party', 'pass', 'past', 'paste', 'patch', 'path', 'patient', 'patrol',
  'pause', 'pave', 'paw', 'pay', 'peace', 'peach', 'peak', 'pear', 'pearl', 'peck',
  'pedal', 'peel', 'peer', 'pen', 'pencil', 'penny', 'people', 'pepper', 'per', 'perch',
  'perfect', 'period', 'permit', 'person', 'pet', 'phase', 'phone', 'photo', 'phrase', 'piano',
  'pick', 'picnic', 'picture', 'pie', 'piece', 'pig', 'pile', 'pill', 'pilot', 'pin',
  'pinch', 'pine', 'pink', 'pint', 'pipe', 'pit', 'pitch', 'pity', 'pixel', 'place',
  'plague', 'plain', 'plan', 'plane', 'plank', 'plant', 'plate', 'play', 'plaza', 'plea',
  'plead', 'please', 'pledge', 'plenty', 'plot', 'plow', 'plug', 'plum', 'plus', 'pocket',
  'poem', 'poet', 'point', 'poison', 'pole', 'police', 'policy', 'polish', 'polite', 'poll',
  'pond', 'pony', 'pool', 'poor', 'pop', 'porch', 'pork', 'port', 'pose', 'post',
  'pot', 'potato', 'pouch', 'pound', 'pour', 'powder', 'power', 'praise', 'pray', 'preach',
  'press', 'pretty', 'price', 'pride', 'prime', 'print', 'prior', 'prize', 'probe', 'problem',
  'profit', 'prompt', 'proof', 'proper', 'proud', 'prove', 'public', 'pull', 'pulse', 'pump',
  'punch', 'pupil', 'pure', 'purple', 'purse', 'push', 'put', 'puzzle', 'quart', 'queen',
  'query', 'quest', 'queue', 'quick', 'quiet', 'quilt', 'quit', 'quite', 'quiz', 'quota',
  'quote', 'rabbit', 'race', 'rack', 'radar', 'radio', 'raft', 'rag', 'rage', 'raid',
  'rail', 'rain', 'raise', 'rally', 'ramp', 'ranch', 'range', 'rank', 'rapid', 'rare',
  'rat', 'rate', 'rather', 'ratio', 'raw', 'ray', 'reach', 'react', 'read', 'ready',
  'real', 'realm', 'reap', 'rear', 'reason', 'rebel', 'recall', 'recent', 'recipe', 'record',
  'red', 'reed', 'reef', 'refer', 'reform', 'refuse', 'regard', 'region', 'regret', 'reign',
  'rein', 'reject', 'relax', 'relay', 'relief', 'rely', 'remain', 'remark', 'remote', 'remove',
  'rent', 'repair', 'repeat', 'reply', 'report', 'rescue', 'resist', 'resort', 'rest', 'result',
  'retail', 'retain', 'retire', 'return', 'reveal', 'review', 'reward', 'rhyme', 'rib', 'ribbon',
  'rice', 'rich', 'rid', 'ride', 'ridge', 'rifle', 'right', 'rigid', 'rim', 'ring',
  'rinse', 'riot', 'ripe', 'rise', 'risk', 'ritual', 'rival', 'river', 'road', 'roar',
  'roast', 'rob', 'robe', 'robin', 'robot', 'rock', 'rod', 'role', 'roll', 'roof',
  'room', 'root', 'rope', 'rose', 'rough', 'round', 'route', 'row', 'royal', 'rub',
  'rubber', 'rude', 'rug', 'ruin', 'rule', 'rumor', 'run', 'rural', 'rush', 'rust',
  'sack', 'sad', 'saddle', 'safe', 'sage', 'said', 'sail', 'saint', 'salad', 'sale',
  'salmon', 'salon', 'salt', 'same', 'sample', 'sand', 'sane', 'satin', 'sauce', 'save',
  'saw', 'say', 'scale', 'scan', 'scar', 'scarce', 'scare', 'scarf', 'scene', 'scent',
  'scheme', 'school', 'scold', 'scope', 'score', 'scout', 'scrap', 'screen', 'screw', 'script',
  'scroll', 'sea', 'seal', 'seam', 'search', 'season', 'seat', 'second', 'secret', 'sect',
  'secure', 'see', 'seed', 'seek', 'seem', 'seen', 'seize', 'seldom', 'select', 'self',
  'sell', 'send', 'senior', 'sense', 'sent', 'series', 'serve', 'set', 'settle', 'seven',
  'sever', 'sew', 'shade', 'shadow', 'shaft', 'shake', 'shall', 'shame', 'shape', 'share',
  'shark', 'sharp', 'shave', 'shed', 'sheep', 'sheer', 'sheet', 'shelf', 'shell', 'shield',
  'shift', 'shine', 'ship', 'shirt', 'shock', 'shoe', 'shoot', 'shop', 'shore', 'short',
  'shot', 'should', 'shout', 'show', 'shower', 'shrimp', 'shut', 'shy', 'sick', 'side',
  'siege', 'sigh', 'sight', 'sign', 'signal', 'silent', 'silk', 'silly', 'silver', 'simple',
  'since', 'sing', 'single', 'sink', 'sir', 'sister', 'sit', 'site', 'six', 'size',
  'skate', 'sketch', 'ski', 'skill', 'skin', 'skip', 'skirt', 'skull', 'sky', 'slab',
  'slam', 'slang', 'slap', 'slate', 'slave', 'sleep', 'sleeve', 'slice', 'slide', 'slight',
  'slim', 'slip', 'slope', 'slot', 'slow', 'small', 'smart', 'smash', 'smell', 'smile',
  'smoke', 'smooth', 'snack', 'snail', 'snake', 'snap', 'sneak', 'snow', 'soak', 'soap',
  'soar', 'social', 'sock', 'soda', 'sofa', 'soft', 'soil', 'solar', 'sold', 'sole',
  'solid', 'solve', 'some', 'son', 'song', 'soon', 'sort', 'soul', 'sound', 'soup',
  'sour', 'source', 'south', 'space', 'spare', 'spark', 'speak', 'spear', 'speech', 'speed',
  'spell', 'spend', 'spent', 'spice', 'spider', 'spill', 'spin', 'spine', 'spirit', 'spite',
  'split', 'spoil', 'spoke', 'sponge', 'spoon', 'sport', 'spot', 'spray', 'spread', 'spring',
  'sprint', 'spy', 'square', 'squeeze', 'stable', 'stack', 'staff', 'stage', 'stain', 'stair',
  'stake', 'stale', 'stalk', 'stall', 'stamp', 'stand', 'star', 'stare', 'start', 'state',
  'stay', 'steady', 'steal', 'steam', 'steel', 'steep', 'steer', 'stem', 'step', 'stern',
  'stick', 'stiff', 'still', 'sting', 'stir', 'stock', 'stone', 'stool', 'stop', 'store',
  'storm', 'story', 'stove', 'strap', 'straw', 'stray', 'stream', 'street', 'stress', 'strict',
  'stride', 'strike', 'string', 'strip', 'stroke', 'strong', 'struck', 'stuck', 'study', 'stuff',
  'stump', 'style', 'sugar', 'suit', 'sum', 'summer', 'sun', 'super', 'supply', 'support',
  'sure', 'surf', 'surge', 'survey', 'swamp', 'swan', 'swap', 'swarm', 'swear', 'sweat',
  'sweep', 'sweet', 'swell', 'swift', 'swim', 'swing', 'switch', 'sword', 'symbol', 'table',
  'tackle', 'tag', 'tail', 'take', 'tale', 'talk', 'tall', 'tame', 'tank', 'tap',
  'tape', 'target', 'task', 'taste', 'tax', 'tea', 'teach', 'team', 'tear', 'tease',
  'tech', 'teeth', 'tell', 'temper', 'temple', 'ten', 'tenant', 'tend', 'tender', 'tennis',
  'tense', 'tent', 'term', 'test', 'text', 'than', 'thank', 'that', 'theft', 'their',
  'theme', 'then', 'theory', 'there', 'these', 'they', 'thick', 'thief', 'thigh', 'thin',
  'thing', 'think', 'third', 'thirst', 'this', 'thorn', 'those', 'though', 'thread', 'threat',
  'three', 'threw', 'thrill', 'throat', 'throne', 'through', 'throw', 'thumb', 'thus', 'tick',
  'ticket', 'tide', 'tidy', 'tie', 'tiger', 'tight', 'tile', 'till', 'tilt', 'timber',
  'time', 'tin', 'tiny', 'tip', 'tire', 'title', 'toad', 'toast', 'today', 'toe',
  'toil', 'token', 'told', 'toll', 'tomato', 'ton', 'tone', 'tongue', 'tonight', 'took',
  'tool', 'tooth', 'top', 'topic', 'torch', 'torn', 'total', 'touch', 'tough', 'tour',
  'toward', 'towel', 'tower', 'town', 'toxic', 'toy', 'trace', 'track', 'trade', 'trail',
  'train', 'trait', 'tramp', 'trap', 'trash', 'travel', 'tray', 'treat', 'tree', 'trend',
  'trial', 'tribe', 'trick', 'tried', 'trim', 'trip', 'troop', 'trophy', 'trouble', 'truck',
  'true', 'trunk', 'trust', 'truth', 'try', 'tube', 'tuck', 'tug', 'tulip', 'tumble',
  'tune', 'tunnel', 'turkey', 'turn', 'turtle', 'twelve', 'twenty', 'twice', 'twin', 'twist',
  'two', 'type', 'ugly', 'ultra', 'uncle', 'under', 'undo', 'unfair', 'union', 'unique',
  'unit', 'unite', 'unity', 'unless', 'until', 'upon', 'upper', 'upset', 'urban', 'urge',
  'use', 'used', 'useful', 'user', 'usual', 'utter', 'vacant', 'vague', 'vain', 'valid',
  'valley', 'value', 'valve', 'van', 'vanish', 'vapor', 'vary', 'vase', 'vast', 'veil',
  'vein', 'velvet', 'vendor', 'venture', 'verb', 'verse', 'very', 'vessel', 'veteran', 'via',
  'vice', 'victim', 'video', 'view', 'villa', 'village', 'vine', 'vinyl', 'violin', 'virtue',
  'virus', 'visa', 'visit', 'vital', 'vivid', 'vocal', 'voice', 'void', 'volume', 'vote',
  'vowel', 'voyage', 'wade', 'wag', 'wage', 'wagon', 'waist', 'wait', 'wake', 'walk',
  'wall', 'wallet', 'walnut', 'wander', 'want', 'war', 'ward', 'ware', 'warm', 'warn',
  'warp', 'wash', 'wasp', 'waste', 'watch', 'water', 'wave', 'wax', 'way', 'weak',
  'wealth', 'weapon', 'wear', 'weary', 'weather', 'weave', 'web', 'wed', 'wedge', 'weed',
  'week', 'weigh', 'weight', 'weird', 'well', 'west', 'wet', 'whale', 'wharf', 'wheat',
  'wheel', 'when', 'where', 'which', 'while', 'whip', 'whirl', 'whisk', 'white', 'who',
  'whole', 'whom', 'whose', 'why', 'wide', 'widow', 'width', 'wife', 'wild', 'will',
  'win', 'wind', 'window', 'wine', 'wing', 'wink', 'winter', 'wipe', 'wire', 'wise',
  'wish', 'wit', 'witch', 'with', 'within', 'without', 'witness', 'wolf', 'woman', 'women',
  'wonder', 'wood', 'wool', 'word', 'work', 'world', 'worm', 'worry', 'worse', 'worth',
  'would', 'wound', 'wrap', 'wreck', 'wrist', 'write', 'wrong', 'wrote', 'yard', 'yarn',
  'yawn', 'year', 'yeast', 'yell', 'yellow', 'yes', 'yet', 'yield', 'yoga', 'yolk',
  'you', 'young', 'your', 'youth', 'zeal', 'zebra', 'zero', 'zinc', 'zone', 'zoo',
];

const lookup = new Set(ANAGRAM_WORDS);

export function isAnagramWord(word: string) {
  return lookup.has(word.toLowerCase());
}

const POOLS = [
  'trances',
  'planets',
  'markets',
  'strange',
  'cluster',
  'painted',
  'restock',
  'gardens',
  'blaster',
  'castles',
  'monster',
  'trailed',
  'shorten',
  'creator',
  'pastime',
  'diverts',
  'flowers',
  'harvest',
  'nectars',
  'sparkle',
];

export function randomPool() {
  const base = POOLS[Math.floor(Math.random() * POOLS.length)];
  return base.split('').sort(() => Math.random() - 0.5);
}

export function canBuild(word: string, pool: string[]) {
  const counts = new Map<string, number>();
  for (const letter of pool) counts.set(letter, (counts.get(letter) ?? 0) + 1);

  for (const letter of word) {
    const left = counts.get(letter) ?? 0;
    if (left === 0) return false;
    counts.set(letter, left - 1);
  }

  return true;
}

export function pointsFor(word: string) {
  const table: Record<number, number> = { 3: 1, 4: 2, 5: 4, 6: 6, 7: 10 };
  return table[word.length] ?? 0;
}

export function bestPossible(pool: string[]) {
  let total = 0;

  for (const word of ANAGRAM_WORDS) {
    if (canBuild(word, pool)) total += pointsFor(word);
  }

  return total;
}
